package com.example.demo.student;

import java.util.Optional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
public class StudentService {

   @Autowired // This means to get the bean called studentRepo Which is auto-generated by Spring, we will use it to handle the data
   private StudentRepo studentRepo;
    
    public Iterable<Student> getStudents() {
		return studentRepo.findAll();
	}

	public Iterable<Student> getStudentsByName(String name) {
		return studentRepo.findByName(name);
	}

	public String addStudent(String name, String email, Integer age) {
		Student newStudent = new Student(name, email, age);
        studentRepo.save(newStudent);
        return "Success";
	}

	public Student updateStudentEmail(Long id, String email) {
		Optional<Student> tobeUpdated =  studentRepo.findById(id);
		if(tobeUpdated.isPresent()) {
			tobeUpdated.get().setEmail(email);
			studentRepo.save(tobeUpdated.get());
		}
		return tobeUpdated.get();
	}

	public String deleteStudent(Long id) {
		studentRepo.deleteById(id);
		return "success";
	}
}
